
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txoeoxvtuietfrhqacmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4b2VveHZ0dWlldGZyaHFhY21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTkwMDcsImV4cCI6MjA2MDgzNTAwN30.Zdg-7EvaSP5geisnXM4sRhtpiBRcDi75KOBqHGL_qQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
